/*
 * Copyright 2021 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.codelab.basics.ui.theme

import androidx.compose.ui.graphics.Color

val Navy = Color(0xFF073042)
val Blue = Color(0xFF4285F4)
val LightBlue = Color(0xFFD7EFFE)
val Chartreuse = Color(0xFFEFF7CF)

val purple200 = Color(0xFFBB86FC)
val purple500 = Color(0xFF6200EE)
val purple700 = Color(0xFF3700B3)
val teal200 = Color(0xFF03DAC5)
val cardCollapsedBackgroundColor = Color(0xFFFEFFFD)
val cardExpandedBackgroundColor = Color(0xFF94CADF)



val md_theme_light_primary = Color(0xFF825500)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDDB3)
val md_theme_light_onPrimaryContainer = Color(0xFF291800)
val md_theme_light_secondary = Color(0xFF6F5B40)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFBDEBC)
val md_theme_light_onSecondaryContainer = Color(0xFF271904)
val md_theme_light_tertiary = Color(0xFF51643F)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD4EABB)
val md_theme_light_onTertiaryContainer = Color(0xFF102004)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1F1B16)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1F1B16)
val md_theme_light_surfaceVariant = Color(0xFFF0E0CF)
val md_theme_light_onSurfaceVariant = Color(0xFF4F4539)
val md_theme_light_outline = Color(0xFF817567)
val md_theme_light_inverseOnSurface = Color(0xFFF9EFE7)
val md_theme_light_inverseSurface = Color(0xFF34302A)
val md_theme_light_inversePrimary = Color(0xFFFFB951)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF825500)
val md_theme_light_outlineVariant = Color(0xFFD3C4B4)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB951)
val md_theme_dark_onPrimary = Color(0xFF452B00)
val md_theme_dark_primaryContainer = Color(0xFF633F00)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDDB3)
val md_theme_dark_secondary = Color(0xFFDDC2A1)
val md_theme_dark_onSecondary = Color(0xFF3E2D16)
val md_theme_dark_secondaryContainer = Color(0xFF56442A)
val md_theme_dark_onSecondaryContainer = Color(0xFFFBDEBC)
val md_theme_dark_tertiary = Color(0xFFB8CEA1)
val md_theme_dark_onTertiary = Color(0xFF243515)
val md_theme_dark_tertiaryContainer = Color(0xFF3A4C2A)
val md_theme_dark_onTertiaryContainer = Color(0xFFD4EABB)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1F1B16)
val md_theme_dark_onBackground = Color(0xFFEAE1D9)
val md_theme_dark_surface = Color(0xFF1F1B16)
val md_theme_dark_onSurface = Color(0xFFEAE1D9)
val md_theme_dark_surfaceVariant = Color(0xFF4F4539)
val md_theme_dark_onSurfaceVariant = Color(0xFFD3C4B4)
val md_theme_dark_outline = Color(0xFF9C8F80)
val md_theme_dark_inverseOnSurface = Color(0xFF1F1B16)
val md_theme_dark_inverseSurface = Color(0xFFEAE1D9)
val md_theme_dark_inversePrimary = Color(0xFF825500)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB951)
val md_theme_dark_outlineVariant = Color(0xFF4F4539)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF825500)



val md_db__theme_light_onPrimary =Color(0xFFFFFF)
val md_db__theme_light_primaryContainer =Color(0xCEE5FF)
val md_db__theme_light_onPrimaryContainer =Color(0x001D32)
val md_db__theme_light_secondary =Color(0x00639A)
val md_db__theme_light_onSecondary =Color(0xFFFFFF)
val md_db__theme_light_secondaryContainer =Color(0xCEE5FF)
val md_db__theme_light_onSecondaryContainer =Color(0x001D32)
val md_db__theme_light_tertiary =Color(0x68587A)
val md_db__theme_light_onTertiary =Color(0xFFFFFF)
val md_db__theme_light_tertiaryContainer =Color(0xEEDBFF)
val md_db__theme_light_onTertiaryContainer =Color(0x231533)
val md_db__theme_light_error =Color(0xBA1A1A)
val md_db__theme_light_errorContainer =Color(0xFFDAD6)
val md_db__theme_light_onError =Color(0xFFFFFF)
val md_db__theme_light_onErrorContainer =Color(0x410002)
val md_db__theme_light_background =Color(0xFCFCFF)
val md_db__theme_light_onBackground =Color(0x1A1C1E)
val md_db__theme_light_surface =Color(0xFCFCFF)
val md_db__theme_light_onSurface =Color(0x1A1C1E)
val md_db__theme_light_surfaceVariant =Color(0xDEE3EB)
val md_db__theme_light_onSurfaceVariant =Color(0x42474E)
val md_db__theme_light_outline =Color(0x72777F)
val md_db__theme_light_inverseOnSurface =Color(0xF0F0F4)
val md_db__theme_light_inverseSurface =Color(0x2F3033)
val md_db__theme_light_inversePrimary =Color(0x96CCFF)
val md_db__theme_light_shadow =Color(0x000000)
val md_db__theme_light_surfaceTint =Color(0x00639A)
val md_db__theme_light_outlineVariant =Color(0xC2C7CF)
val md_db__theme_light_scrim =Color(0x000000)
val md_db__theme_dark_primary =Color(0x96CCFF)
val md_db__theme_dark_onPrimary =Color(0x003353)
val md_db__theme_dark_primaryContainer =Color(0x004A75)
val md_db__theme_dark_onPrimaryContainer =Color(0xCEE5FF)
val md_db__theme_dark_secondary =Color(0x96CCFF)
val md_db__theme_dark_onSecondary =Color(0x003353)
val md_db__theme_dark_secondaryContainer =Color(0x004A76)
val md_db__theme_dark_onSecondaryContainer =Color(0xCEE5FF)
val md_db__theme_dark_tertiary =Color(0xD3BFE6)
val md_db__theme_dark_onTertiary =Color(0x382A49)
val md_db__theme_dark_tertiaryContainer =Color(0x4F4061)
val md_db__theme_dark_onTertiaryContainer =Color(0xEEDBFF)
val md_db__theme_dark_error =Color(0xFFB4AB)
val md_db__theme_dark_errorContainer =Color(0x93000A)
val md_db__theme_dark_onError =Color(0x690005)
val md_db__theme_dark_onErrorContainer =Color(0xFFDAD6)
val md_db__theme_dark_background =Color(0x1A1C1E)
val md_db__theme_dark_onBackground =Color(0xE2E2E5)
val md_db__theme_dark_surface =Color(0x1A1C1E)
val md_db__theme_dark_onSurface =Color(0xE2E2E5)
val md_db__theme_dark_surfaceVariant =Color(0x42474E)
val md_db__theme_dark_onSurfaceVariant =Color(0xC2C7CF)
val md_db__theme_dark_outline =Color(0x8C9198)
val md_db__theme_dark_inverseOnSurface =Color(0x1A1C1E)
val md_db__theme_dark_inverseSurface =Color(0xE2E2E5)
val md_db__theme_dark_inversePrimary =Color(0x00639A)
val md_db__theme_dark_shadow =Color(0x000000)
val md_db__theme_dark_surfaceTint =Color(0x96CCFF)
val md_db__theme_dark_outlineVariant =Color(0x42474E)
val md_db__theme_dark_scrim =Color(0x000000)
val CustomColor12 =Color(0x008DCA)
